version: "3"

services:

  # Okk Url Ui
  okk-url-ui:
    image: "bstk/okk-url-ui:latest"
    container_name: "okk-url-ui"
    ports:
      - "4200:80"

  # Okk Url Spring
  okk-url-backend:
    image: "bstk/okk-url-spring"
    container_name: "okk-url-spring"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    environment:
      - "SPRING_REDIS_HOST=redis"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/okk-url-db"

    networks:
      - okk-url

  # ProtgreSql
  postgresql:
    image: "postgres:14.1"
    container_name: "okk-url-postgresql"
    ports:
      - "5432:5432"
    networks:
      - okk-url
    environment:
      - "POSTGRES_DB=okk-url-db"
      - "POSTGRES_USER=okk-url-db"
      - "POSTGRES_PASSWORD=okk-url-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 5s
      timeout: 5s
      retries: 6

  # Cache Redis
  redis:
    image: redis:6.2-alpine
    container_name: "okk-url-redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - okk-url
    command: redis-server --save 20 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  okk-url:
    driver: bridge